[package]
org = "sansi"
name = "server"
version = "0.1.0"
distribution = "2201.10.0"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
path = "E:\\Utility Software\\SQL\\mysql-connector-j-9.0.0\\mysql-connector-j-9.0.0.jar"
groupId = "mysql"
artifactId = "mysql-connector-java"
version = "8.0.26"
