INSERT INTO medications (name, dosage_form, dosage_strength, shape, known_brands) VALUES
('lenalidomide', 'Capsule', '25 mg', 'Oblong', 'Revlimid'),
('thalidomide', 'Capsule', '50 mg', 'Oblong', 'Thalomid'),
('abiraterone', 'Tablet', '250 mg; 500 mg', 'Oval', 'Zytiga'),
('anastrozole', 'Tablet', '1 mg', 'Round', 'Arimidex'),
('bicalutamide', 'Tablet', '50 mg', 'Round', 'Casodex'),
('dexamethasone', 'Tablet', '2 mg; 4 mg', 'Five-sided', 'Decadron, DexPak 6 DayTaperpak, Hemady'),
('prednisolone', 'Tablet', '5 mg; 25 mg', 'Round', 'Flo-Pred, Millipred, Orapred, Pediapred, Veripred 20'),
('tamoxifen', 'Tablet', '10 mg; 20 mg', 'Round', 'Soltamox'),
('allopurinol', 'Tablet', '100 mg; 300 mg', 'Round', 'Zyloprim, Lopurin, Aloprim'),
('mesna', 'Tablet', '400 mg; 600 mg', 'Round', 'Mesna, Mesnex, Metsina'),
('ferrous salt + folic acid', 'Tablet', '60 mg iron', 'Oblong', NULL),
('methotrexate', 'Tablet', '2.5 mg', 'Oval', 'Trexall, Xatmep'),
('folic acid', 'Tablet', '400 micrograms; 1 mg; 5 mg', 'Round', 'FA-8, Folacin-800, FaLessa, Folvite'),
('dabigatran', 'Capsule', '110 mg; 150 mg', 'Three-sided', NULL),
('phytomenadione', 'Tablet', '10 mg', 'Round', 'Kenadion'),
('warfarin', 'Tablet', '1 mg; 2 mg; 5 mg', 'Oval', 'Coumadin, Jantoven'),
('deferasirox', 'Tablet', '100 mg; 250 mg; 400 mg', 'Oval', 'Ferriprox'),
('bisoprolol', 'Tablet', '1.25 mg; 5 mg', 'Round', 'Zebeta'),
('glyceryl trinitrate', 'Tablet (sublingual)', '500 micrograms', 'Round', NULL),
('isosorbide dinitrate', 'Tablet (sublingual)', '5 mg', 'Round', 'Isochron, Isordil Titradose, Sorbitrate, Dilatrate-SR, Isordil, ISDN, Isordil Tembids'),
('verapamil', 'Tablet', '40 mg; 80 mg', 'Oval', 'Calan, Calan SR, Isoptin SR, Verelan, Verelan PM'),
('digoxin', 'Tablet', '62.5 micrograms; 250 micrograms', 'Round', 'Digitek, Digox, Lanoxin, Lanoxicaps, Cardoxin'),
('acetylsalicylic acid', 'Tablet', '100 mg to 500 mg', 'Round', 'Aspirin'),
('amlodipine', 'Tablet', '5 mg', 'Round', 'Katerzia, Norliqva, Norvasc'),
('sulfasalazine', 'Tablet', '500 mg', 'Round', 'Azulfidine, Azulfidine EN-tabs'),
('enalapril', 'Tablet', '2.5 mg; 5 mg; 10 mg', 'Round', 'Epaned, Vasotec'),
('hydralazine', 'Tablet', '25 mg; 50 mg', 'Round', 'Apresoline'),
('lisinopril', 'Tablet', '10 mg; 20 mg', 'Round', 'Prinivil, Qbrelis, Zestril'),
('hydrochlorothiazide', 'Tablet', '12.5 mg; 25 mg; 50 mg', 'Round', 'HydroDIURIL, Esidrix, Microzide'),
('losartan', 'Tablet', '25 mg; 50 mg; 100 mg', 'Oval', 'Cozaar'),
('methyldopa', 'Tablet', '250 mg', 'Oval', 'Aldomet'),
('telmisartan', 'Tablet', '20 mg; 40 mg; 80 mg', 'Oval', 'Micardis'),
('penicillamine', 'Capsule', '250 mg', 'Oblong', 'Cuprimine, Depen, D-Penamine'),
('hydroxychloroquine', 'Tablet', '200 mg', 'Oval', 'Plaquenil, Quineprox'),
('azathioprine', 'Tablet', '50 mg; 100 mg', 'Round', 'Azasan, Imuran'),
('chloroquine', 'Tablet', '100 mg; 150 mg; 250 mg; 500 mg', 'Round', 'Aralen Phosphate, Aralen Hydrochloride'),
('furosemide', 'Tablet', '20 mg; 40 mg', 'Round', 'Lasix, Diaqua-2, Lo-Aqua, Furoscix'),
('thiamine', 'Tablet', '50 mg', 'Round', 'Vitamin B1'),
('spironolactone', 'Tablet', '25 mg', 'Round', 'Aldactone, CaroSpir'),
('riboflavin', 'Tablet', '5 mg', 'Round', 'B2-400, Vitamin B2, Riboson'),
('retinol', 'Capsule', '50 000 IU; 100 000 IU; 200 000 IU', 'Oblong', 'Vitamin A'),
('clopidogrel', 'Tablet', '75 mg; 300 mg', 'Round', 'Plavix'),
('simvastatin', 'Tablet', '5 mg; 10 mg; 20 mg; 40 mg', 'Round', 'Zocor'),
('pyridoxine', 'Tablet', '25 mg', 'Round', 'Vitamin B6, Vitelle Nestrex, Pyridoxal'),
('amiloride', 'Tablet', '5 mg', 'Four-sided', 'Midamor'),
('nicotinamide', 'Tablet', '50 mg', 'Oval', 'Nicoglow'),
('colecalciferol', 'Capsule', '400 IU; 1000 IU', 'Oblong', 'Calcidol, Calciferol, Drisdol'),
('calcium', 'Tablet', '500 mg', 'Oval', NULL),
('ascorbic acid', 'Tablet', '500 mg', 'Round', 'Acerola, Ascorbic Acid Quick Melts, Cemill 1000, C-Time, Easy-C'),
('ranitidine', 'Tablet', '150 mg', 'Round', 'Zantac'),
('metoclopramide', 'Tablet', '10 mg', 'Round', 'Metozolv ODT, Reglan'),
('metformin', 'Tablet', '500 mg', 'Round', 'Fortamet, Glucophage, Glucophage XR, Glumetza, Riomet'),
('diazoxide', 'Tablet', '50 mg', 'Oval', NULL),
('levothyroxine', 'Tablet', '25 micrograms; 50 micrograms; 100 micrograms', 'Oblong', 'Ermeza, Euthyrox, Levo-T, Levoxyl, Synthroid'),
('potassium iodide', 'Tablet', '60 mg', 'Oval', 'ThyroSafe, ThyroShield, Pima'),
('methimazole', 'Tablet', '5 mg; 10 mg; 20 mg', 'Round', 'Tapazole, Northyx'),
('propylthiouracil', 'Tablet', '50 mg', 'Round', NULL),
('varenicline', 'Tablet', '0.5 mg; 1 mg', 'Round', 'Chantix'),
('bupropion', 'Tablet', '150 mg', 'Round', 'Wellbutrin, Wellbutrin SR, Wellbutrin XL, Zyban, Aplenzin, Budeprion XL, Forfivo XL'),
('cabergoline', 'Tablet', '0.5 mg; 1 mg', 'Oval', 'Dostinex'),
('pyridostigmine', 'Tablet', '60 mg', 'Oblong', 'Mestinon, Mestinon Timespan, Regonol'),
('acetazolamide', 'Tablet', '250 mg', 'Round', 'Diamox, Diamox Sequels'),
('ethinylestradiol + levonorgestrel', 'Tablet', '30 micrograms + 150 micrograms', 'Round', NULL),
('ethinylestradiol + norethisterone', 'Tablet', '35 micrograms + 1 mg', 'Round', 'Norimin, Synphase'),
('clomifene citrate', 'Tablet', '50 mg', 'Round', 'Duinum, Clomish, Clomid'),
('mifepristone', 'Tablet', '200 mg', 'Oval', 'Mifeprex, Korlym'),
('misoprostol', 'Tablet', '200 micrograms', 'Six-sided', 'Cytotec'),
('haloperidol', 'Tablet', '2 mg; 5 mg', 'Round', 'Haldol'),
('chlorpromazine', 'Tablet', '25 mg; 100 mg', 'Round', 'Thorazine'),
('olanzapine', 'Tablet', '5 mg; 10 mg', 'Oval', 'Zyprexa'),
('sertraline', 'Tablet', '50 mg; 100 mg', 'Oval', 'Zoloft, Lustral'),
('haloperidol', 'Tablet', '5 mg', 'Round', 'Haldol'),
('amitriptyline', 'Tablet', '25 mg; 50 mg; 75 mg (hydrochloride)', 'Round', 'Elavil, Endep, Vanatrip'),
('carbamazepine', 'Tablet (scored)', '100 mg; 200 mg; 400 mg', 'Round/Oblong', 'Epitol, Equetro, Tegretol, Tegretol XR'),
('quetiapine', 'Tablet (immediate-release); Tablet (modified-release)', '25 mg; 100 mg; 150 mg; 200 mg; 300 mg (immediate); 50 mg; 150 mg; 200 mg; 300 mg; 400 mg (modified)', 'Round', 'Seroquel, Seroquel XR'),
('fluoxetine', 'Solid oral dosage form', '20 mg (as hydrochloride)', 'Capsule/Oblong', 'Prozac, Sarafem, Rapiflux, Selfemra'),
('valproic acid (sodium valproate)', 'Tablet (enteric-coated)', '200 mg; 500 mg', 'Capsule/Oblong', 'Valproate Sodium, Depakene, Depacon, Stavzor'),
('diazepam', 'Tablet (scored)', '2 mg; 5 mg', 'Round', 'Valium'),
('acamprosate calcium', 'Tablet', '333 mg', 'Round', NULL),
('naltrexone', 'Tablet', '50 mg', 'Oval', 'Vivitrol, Naltrexone Tablets'),
('amiodarone hydrochloride', 'Tablet', '100 mg; 200 mg; 400 mg', 'Round/Oval', NULL);