INSERT INTO medications (name, dosage_form, dosage_strength, shape, brand) VALUES
('acetylsalicylic acid', 'Tablet', '100 mg to 500 mg', 'Round', 'Zorprin'),
('ibuprofen', 'Tablet', '200 mg; 400 mg; 600 mg', 'Round/Oblong', 'Advil'),
('paracetamol (acetaminophen)', 'Suppository/Tablet/Tablet (dispersible)', '100 mg; 250 mg; 325 mg; 500 mg', 'Round/Oblong', 'Tylenol'),
('codeine', 'Tablet', '30 mg (phosphate)', 'Round', 'Ascomp'),
('morphine', 'Tablet (slow release/immediate release)', '10 mg to 200 mg (hydrochloride/sulfate)', 'Round/Oval', 'MSiR'),
('methadone', 'Tablet', '5 mg; 10 mg (hydrochloride)', 'Round/Oblong', 'Methadose'),
('amitriptyline', 'Tablet', '10 mg; 25 mg; 75 mg', 'Round', 'Elavil'),
('cyclizine', 'Tablet', '50 mg', 'Round', 'Marezine'),
('dexamethasone', 'Tablet', '2 mg; 4 mg', 'Round/Five-sided', 'Decadron'),
('diazepam', 'Tablet', '5 mg; 10 mg', 'Round', 'Valium'),
('docusate sodium', 'Capsule', '100 mg', 'Oval', 'Citranatal Harmony'),
('fluoxetine', 'Solid oral dosage form', '20 mg (as hydrochloride)', 'Oblong', 'Prozac'),
('haloperidol', 'Solid oral dosage form', '0.5 mg; 2 mg; 5 mg', 'Round', 'Haldol'),
('loperamide', 'Solid oral dosage form', '2 mg', 'Oblong', 'Imodium'),
('metoclopramide', 'Solid oral form', '10 mg (hydrochloride)', 'Round', 'Reglan'),
('Midazolam', 'Solid oral dosage form', '7.5 mg; 15 mg', 'Oblong', 'Versed'),
('ondansetron', 'Solid oral dosage form', 'Eq 4 mg; Eq 8 mg; Eq 24 mg', 'Round', 'Zofran'),
('Aprepitant', 'Capsule', '80 mg; 125 mg; 165 mg', 'Oblong', 'Aponvie'),
('sulfasalazine', 'Tablet', '500 mg', 'Round', 'Azulfidine'),
('senna', 'Tablet', '7.5 mg (sennosides)', 'Round', 'Senokot'),
('zinc sulfate', 'Solid oral dosage form', '20 mg', 'Round', 'Orazinc'),
('fludrocortisone', 'Tablet', '100 micrograms (acetate)', 'Round/Oval', 'Florinef'),
('Hydrocortisone', 'Tablet', '5 mg; 10 mg; 20 mg', 'Round/Oval', 'Hydrocort'),
('medroxyprogesterone acetate', 'Tablet', '5 mg', 'Round', 'DepoProvera'),
('empagliflozin', 'Tablet', '10 mg; 25 mg', 'Round/Oval', 'Jardiance'),
('gliclazide', 'Solid oral dosage form', '30 mg; 60 mg; 80 mg', 'Round', 'Dacadis'),
('loratadine', 'Tablet', '10 mg', 'Round/Oval', 'Claritin'),
('carbamazepine', 'Tablet (chewable/scored)', '100 mg; 200 mg; 400 mg', 'Round/Oblong', 'Tegretol'),
('lamotrigine', 'Tablet (chewable/dispersible)', '2 mg; 5 mg; 25 mg; 50 mg; 100 mg; 200 mg', 'Round/Triangle', 'Lamictal'),
('levetiracetam', 'Tablet', '250 mg; 500 mg; 750 mg; 1000 mg', 'Oblong', 'Keppra'),
('phenobarbital', 'Tablet', '15 mg to 100 mg', 'Round', 'Phenobarbitone'),
('phenytoin', 'Solid oral dosage form/Tablet (chewable)', '25 mg; 50 mg; 100 mg', 'Oblong', 'Dilantin'),
('valproic acid (sodium valproate)', 'Tablet (crushable/enteric-coated)', '100 mg; 200 mg; 500 mg', 'Oblong/Oval', 'Belvo'),
('ethosuximide', 'Capsule', '250 mg', 'Oval/Oblong', 'Zarontin'),
('cladribine', 'Tablet', '10 mg', 'Round', 'Mavenclad'),
('biperiden', 'Tablet', '2 mg (hydrochloride)', 'Round', 'Akineton'),
('albendazole', 'Tablet (chewable/scored)', '400 mg', 'Round', 'Albenza'),
('ivermectin', 'Tablet', '3 mg', 'Round', 'Heartgard'),
('levamisole', 'Tablet', '50 mg; 150 mg (hydrochloride)', 'Round/Oblong', 'Ergamisol'),
('mebendazole', 'Tablet (chewable)', '100 mg; 500 mg', 'Round', 'Mebendazole (Emverm)'),
('niclosamide', 'Tablet (chewable)', '500 mg', 'Round', 'Niclocide'),
('praziquantel', 'Tablet/Tablet (scored)', '150 mg; 500 mg; 600 mg', 'Oblong', 'Biltricide'),
('pyrantel', 'Tablet (chewable)', '250 mg (as embonate or pamoate)', 'Round', 'Pronto Plus Pinworm'),
('albendazole', 'Tablet (chewable/scored)', '400 mg', 'Round', 'Albenza'),
('diethylcarbamazine', 'Tablet', '50 mg; 100 mg (dihydrogen citrate)', 'Round', 'Hetrazan'),
('ivermectin', 'Tablet', '3 mg', 'Round', 'Heartgard'),
('Triclabendazole', 'Tablet (scored)', '250 mg', 'Oblong', 'Egatan'),
('Amoxicillin', 'Tablet (dispersible/scored)', '250 mg; 500 mg (as trihydrate)', 'Oblong', 'Amoxi'),
('Cephalexin', 'Solid oral dosage form/Tablet (dispersible)', '125 mg; 250 mg; 500 mg', 'Oblong', 'Biocef'),
('Clindamycin', 'Capsule', '150 mg (as hydrochloride)', 'Oblong', 'Cleocin'),
('Cloxacillin', 'Capsule', '250 mg; 500 mg; 1 g (as sodium)', 'Oblong', 'Cloxapen'),
('Doxycycline', 'Solid oral dosage form/Tablet (dispersible)', '50 mg; 100 mg (as hyclate/monohydrate)', 'Round/Oblong', 'Vibramycin-D'),
('Metronidazole', 'Tablet', '200 mg; 250 mg; 400 mg; 500 mg', 'Oblong', 'Acea'),
('Phenoxymethylpenicillin', 'Solid oral dosage form', '250 mg; 500 mg (as potassium)', 'Round', 'Penicillin V'),
('Trimethoprim', 'Tablet', '100 mg; 200 mg', 'Round', 'Primsol'),
('Azithromycin', 'Solid oral dosage form', '250 mg; 500 mg (anhydrous)', 'Oval', 'Zithromax'),
('Cefixime', 'Solid oral dosage form', '200 mg; 400 mg (as trihydrate)', 'Oblong', 'Suprax'),
('Ciprofloxacin', 'Solid oral dosage form', '100 mg; 250 mg; 500 mg (as hydrochloride)', 'Round/Oblong', 'Ciproxin'),
('Clarithromycin', 'Solid oral dosage form', '250 mg; 500 mg', 'Round/Oblong', 'Biaxin'),
('vancomycin', 'Capsule', '125 mg; 250 mg (as hydrochloride)', 'Oblong', 'Vancocin'),
('linezolid', 'Tablet/Tablet (dispersible)', '150 mg; 600 mg', 'Oval/Oblong', 'Zyvox'),
('clofazimine', 'Solid oral dosage form', '50 mg; 100 mg', 'Oblong', 'Lamprene'),
('dapsone', 'Tablet', '25 mg; 50 mg; 100 mg', 'Round', 'Aczone'),
('rifampin', 'Solid oral dosage form', '150 mg; 300 mg', 'Oblong', 'Rifadin'),
('ethambutol', 'Tablet', '100 mg; 400 mg (hydrochloride)', 'Round', 'Myambutol'),
('ethionamide', 'Tablet/Tablet (dispersible)', '125 mg; 250 mg', 'Round', 'Trecator'),
('isoniazid', 'Tablet/Tablet (dispersible)', '100 mg; 300 mg', 'Round', 'Isoniazid'),
('Pyrazinamide', 'Tablet', '400 mg', 'Round', 'Pyra'),
('bedaquiline', 'Tablet', '100 mg', 'Round', 'Sirturo'),
('Clofazimine', 'Solid oral dosage form', '50 mg; 100 mg', 'Oblong', 'Lamprene');
